development:
  clients:
    default:
      database: WSD2021
      hosts:
        -  cluster0-shard-00-01.p223e.mongodb.net:27017 
      options:
        user: 'wsd2021'
        password: 'wsd2021' 
        auth_source: admin    
        ssl: true
        ssl_verify: false

production:
  clients:
    default:
      database: WSD2021
      hosts:
        -  cluster0-shard-00-01.p223e.mongodb.net:27017 
      options:
        user: 'wsd2021'
        password: 'wsd2021' 
        auth_source: admin    
        ssl: true
        ssl_verify: false

test:
  clients:
    default:
      database: WSD2021
      hosts:
        -  cluster0-shard-00-01.p223e.mongodb.net:27017 
      options:
        user: 'wsd2021'
        password: 'wsd2021' 
        auth_source: admin    
        ssl: true
        ssl_verify: false